### ISSUE TITLE
Can't hear anything

### ISSUE THREAD

**Issue by ronilaukkarinen** [bonnici/scrobble-along-scrobbler#1]
Hello, for some reason, when I got to the website and connect my last.fm account and press "scrobble along" I can't hear anything. Nothing peculiar in console. Liking the idea though!

**Comment by bonnici** [comment]
Hi, the scrobbler is just a way to get the songs posted on Last.fm, you'll need to use the stream links to get to the radio streams.

**Comment by ronilaukkarinen** [comment]
Oh, right, I see. I also noticed that after closing the page I see "now playing" on my profile even though I don't have the page open. Is there a way to revoke access? also can I request radio channels to be added? I would like to have Finnish [Radio Rock](http://www.radiorock.fi/#!/info/Nettiradio) :)

**Comment by bonnici** [comment]
You need to log out, click the stop scrobbling button, or wait for the timeout time to run out before it will stop scrobbling. You can also go to the settings on last.fm and revoke access from there. I do take requests! I'll add Radio Rock when I can.
