### ISSUE TITLE
Scraper for OldFashioned Radio is broken?

### ISSUE THREAD

**Issue by simonrommel** [bonnici/scrobble-along-scrobbler#2]
Scrobbling along with any of the OldFashionedRadio stations no longer works (since Sept. 15 2017).

A quick look at the respective scraper in /scrapers/json/OFRscraper.js and the scraped URL therein:
    https://ofr.fm/api/v1/live/#?_=  (where # is the station ID, either of 8000,8004,8008,8012)
suggests the station's API is returning correct JSON at that URL with up to date song data.

The current song display on scrobblealong.com for the OFR stations has not changed since quite some time.

**Comment by bonnici** [comment]
Looks like they changed the show IDs on me. Easily fixed, thanks for finding the right IDs!
